/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExportMetadata {
  'youtubeHashtags' : Array<string>,
  'instagramHashtags' : Array<string>,
  'youtubeTitle' : string,
  'youtubeDescription' : string,
  'instagramCaption' : string,
}
export interface Scene {
  'id' : bigint,
  'visualPrompt' : string,
  'duration' : bigint,
  'order' : bigint,
  'transition' : string,
  'description' : string,
  'caption' : string,
}
export interface Template {
  'name' : string,
  'description' : string,
  'styleHints' : string,
}
export interface TemplateUpdate {
  'status' : string,
  'title' : string,
  'topic' : string,
  'scenes' : Array<Scene>,
  'template' : string,
  'musicStyle' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoProject {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'topic' : string,
  'scenes' : Array<Scene>,
  'userId' : Principal,
  'createdAt' : bigint,
  'exportMetadata' : [] | [ExportMetadata],
  'updatedAt' : bigint,
  'template' : string,
  'musicStyle' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string, string], VideoProject>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'generateExportMetadata' : ActorMethod<[bigint], [] | [ExportMetadata]>,
  'generateScenes' : ActorMethod<[string, string], Array<Scene>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProject' : ActorMethod<[bigint], [] | [VideoProject]>,
  'getTemplates' : ActorMethod<[], Array<Template>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProjectsByUser' : ActorMethod<[Principal], Array<VideoProject>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProject' : ActorMethod<[bigint, TemplateUpdate], [] | [VideoProject]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];