/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Scene = IDL.Record({
  'id' : IDL.Nat,
  'visualPrompt' : IDL.Text,
  'duration' : IDL.Nat,
  'order' : IDL.Nat,
  'transition' : IDL.Text,
  'description' : IDL.Text,
  'caption' : IDL.Text,
});
export const ExportMetadata = IDL.Record({
  'youtubeHashtags' : IDL.Vec(IDL.Text),
  'instagramHashtags' : IDL.Vec(IDL.Text),
  'youtubeTitle' : IDL.Text,
  'youtubeDescription' : IDL.Text,
  'instagramCaption' : IDL.Text,
});
export const VideoProject = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'scenes' : IDL.Vec(Scene),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'exportMetadata' : IDL.Opt(ExportMetadata),
  'updatedAt' : IDL.Int,
  'template' : IDL.Text,
  'musicStyle' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Template = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'styleHints' : IDL.Text,
});
export const TemplateUpdate = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'scenes' : IDL.Vec(Scene),
  'template' : IDL.Text,
  'musicStyle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [VideoProject],
      [],
    ),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateExportMetadata' : IDL.Func([IDL.Nat], [IDL.Opt(ExportMetadata)], []),
  'generateScenes' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Scene)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(VideoProject)], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProjectsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoProject)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func(
      [IDL.Nat, TemplateUpdate],
      [IDL.Opt(VideoProject)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Scene = IDL.Record({
    'id' : IDL.Nat,
    'visualPrompt' : IDL.Text,
    'duration' : IDL.Nat,
    'order' : IDL.Nat,
    'transition' : IDL.Text,
    'description' : IDL.Text,
    'caption' : IDL.Text,
  });
  const ExportMetadata = IDL.Record({
    'youtubeHashtags' : IDL.Vec(IDL.Text),
    'instagramHashtags' : IDL.Vec(IDL.Text),
    'youtubeTitle' : IDL.Text,
    'youtubeDescription' : IDL.Text,
    'instagramCaption' : IDL.Text,
  });
  const VideoProject = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'scenes' : IDL.Vec(Scene),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'exportMetadata' : IDL.Opt(ExportMetadata),
    'updatedAt' : IDL.Int,
    'template' : IDL.Text,
    'musicStyle' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Template = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'styleHints' : IDL.Text,
  });
  const TemplateUpdate = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'scenes' : IDL.Vec(Scene),
    'template' : IDL.Text,
    'musicStyle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [VideoProject],
        [],
      ),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateExportMetadata' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExportMetadata)],
        [],
      ),
    'generateScenes' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Scene)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(VideoProject)], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProjectsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoProject)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func(
        [IDL.Nat, TemplateUpdate],
        [IDL.Opt(VideoProject)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };